import { useEffect, useState } from 'react'
import { authorized, type User } from './auth'
import { translate } from './ui'
type AnalyticsData={data_environment:string;window:{start:string;end_exclusive:string};answer_runs:{total:number;outcomes:Record<string,number>;languages:Record<string,number>};latency:{sample_count:number;excluded_terminal_count:number;mean_ms:number|null;p50_ms:number|null;p95_ms:number|null};feedback:{count:number;votes:Record<string,number>;reasons:Record<string,number>;by_outcome:Record<string,Record<string,number>>;participation_denominator:number;participation_rate:number|null;helpful_rate:number|null};processing:{ingested_versions:number;ingestion_jobs:Record<string,number>;ocr_jobs:Record<string,number>;index_jobs:Record<string,number>;ocr_reviews:Record<string,number>};definitions:Record<string,string>}
const labels:Record<string,[string,string]>={ingestion_jobs:['Ingestion jobs','दस्तावेज़ जोड़ने के कार्य'],ocr_jobs:['OCR jobs','चित्र से पाठ पढ़ने के कार्य'],index_jobs:['Index jobs','खोज सूचकांक के कार्य'],ocr_reviews:['OCR review decisions','चित्र-पाठ समीक्षा निर्णय'],completed:['Completed','पूरा'],answered:['Answered','उत्तर मिला'],partial:['Partial','आंशिक'],abstained:['Insufficient evidence','पर्याप्त साक्ष्य नहीं'],clarification:['Clarification','स्पष्टीकरण'],failed:['Failed','विफल'],done:['Completed','पूरा'],ready:['Ready','तैयार'],accepted:['Accepted','स्वीकृत'],rejected:['Rejected','अस्वीकृत'],error:['Error','त्रुटि'],cancelled:['Cancelled','रद्द'],queued:['Queued','प्रतीक्षा'],processing:['Processing','प्रक्रिया जारी'],unclassified_done:['Unclassified completed','अवर्गीकृत पूर्ण'],en:['English','अंग्रेज़ी'],hi:['Hindi','हिन्दी'],helpful:['Helpful','उपयोगी'],not_helpful:['Not helpful','उपयोगी नहीं'],unspecified:['No reason','कोई कारण नहीं'],unclear_wording:['Unclear wording','अस्पष्ट शब्द'],incomplete_answer:['Incomplete answer','अधूरा उत्तर'],citation_issue:['Citation issue','संदर्भ समस्या'],language_issue:['Language issue','भाषा समस्या'],suspected_factual_error:['Suspected factual error','तथ्य पर संदेह']}
export default function Analytics({user}:{user:User}) {
  const t=translate(user),[days,setDays]=useState(7),[data,setData]=useState<AnalyticsData|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0)
  useEffect(()=>{let disposed=false;setData(null);setError(false);authorized<AnalyticsData>(`/admin/analytics?days=${days}`).then(v=>{if(!disposed)setData(v)}).catch(()=>{if(!disposed)setError(true)});return()=>{disposed=true}},[days,retry])
  const name=(key:string)=>labels[key]?t(...labels[key]):key.replaceAll('_',' ')
  const counts=(values:Record<string,number>)=><dl className="grid grid-cols-2 gap-x-4 gap-y-1">{Object.entries(values).map(([k,v])=><div key={k}><dt className="muted">{name(k)}</dt><dd>{v}</dd></div>)}</dl>
  const rate=(v:number|null)=>v===null?t('Unavailable (no denominator)','उपलब्ध नहीं (हर शून्य है)'):`${(v*100).toFixed(1)}%`
  return <section className="space-y-5"><h1>{t('Admin analytics','प्रशासन आँकड़े')}</h1><p className="notice">{t('Database aggregates only. User satisfaction is not factual accuracy. Feedback remains unavailable as an evidence-quality score.','केवल डेटाबेस के समेकित आँकड़े। संतुष्टि तथ्यात्मक सटीकता नहीं है। प्रतिक्रिया का प्रमाण-गुणवत्ता स्कोर उपलब्ध नहीं है।')}</p>
    <div className="flex flex-wrap items-center gap-3"><label>{t('Rolling window','समय अवधि')} <select className="rounded border p-2" value={days} onChange={e=>setDays(Number(e.target.value))}>{[1,7,30].map(v=><option key={v} value={v}>{v} {t('days','दिन')}</option>)}</select></label><button onClick={()=>setRetry(v=>v+1)}>{t('Refresh','ताज़ा करें')}</button></div>
    {error?<div role="alert" className="notice">{t('Analytics unavailable or access denied.','आँकड़े उपलब्ध नहीं या अनुमति नहीं है।')} <button onClick={()=>setRetry(v=>v+1)}>{t('Retry','फिर कोशिश करें')}</button></div>:!data?<p role="status">{t('Loading aggregates…','आँकड़े खुल रहे हैं…')}</p>:<>{data.data_environment==='isolated_test'&&<p className="notice">{t('Isolated test dataset: these synthetic votes are not production user satisfaction.','अलग परीक्षण डेटा: ये कृत्रिम वोट वास्तविक उपयोगकर्ता संतुष्टि नहीं हैं।')}</p>}<p className="muted">UTC · [{data.window.start}, {data.window.end_exclusive})</p>{!data.answer_runs.total&&<p className="notice">{t('No retained answer runs in this window. Rates and latency are unavailable when no samples exist.','इस अवधि में कोई उत्तर रिकॉर्ड नहीं। नमूने न होने पर दर और समय उपलब्ध नहीं हैं।')}</p>}
      <div className="grid gap-4 md:grid-cols-2"><article className="card"><h2>{t('Answer outcomes','उत्तर परिणाम')} ({data.answer_runs.total})</h2>{counts(data.answer_runs.outcomes)}</article><article className="card"><h2>{t('Response languages','उत्तर की भाषाएँ')}</h2>{counts(data.answer_runs.languages)}</article>
      <article className="card space-y-2"><h2>{t('Recorded worker latency','दर्ज उत्तर-प्रक्रिया समय')}</h2><p>{data.latency.sample_count} {t('samples','नमूने')} · {data.latency.excluded_terminal_count} {t('terminal runs excluded','अंतिम रिकॉर्ड बाहर')}</p>{(['mean_ms','p50_ms','p95_ms'] as const).map(k=><p key={k}>{k.replace('_ms','')}: {data.latency[k]===null?t('Unavailable','उपलब्ध नहीं'):`${data.latency[k]!.toFixed(2)} ms`}</p>)}</article>
      <article className="card space-y-2"><h2>{t('Current feedback','वर्तमान प्रतिक्रिया')} ({data.feedback.count})</h2>{counts(data.feedback.votes)}<p>{t('Participation','भागीदारी')}: {data.feedback.count}/{data.feedback.participation_denominator} · {rate(data.feedback.participation_rate)}</p><p>{t('Helpful votes / all votes','उपयोगी वोट / सभी वोट')}: {data.feedback.votes.helpful}/{data.feedback.count} · {rate(data.feedback.helpful_rate)}</p><p className="muted">{t('Denominator: retained completed answered/partial runs created in this window, including sources later revoked.','हर: इस अवधि में बने, अभी रखे हुए पूर्ण उत्तर/आंशिक उत्तर; बाद में प्रतिबंधित स्रोत भी शामिल हैं।')}</p></article></div>
      <article className="card"><h2>{t('Feedback reasons','प्रतिक्रिया के कारण')}</h2>{counts(data.feedback.reasons)}<h3>{t('By answered/partial outcome','उत्तर/आंशिक परिणाम के अनुसार')}</h3>{Object.entries(data.feedback.by_outcome).map(([k,v])=><div key={k}><h3>{name(k)}</h3>{counts(v)}</div>)}</article>
      <article className="card space-y-3"><h2>{t('Document processing','दस्तावेज़ प्रसंस्करण')}</h2><p>{t('Versions ingested','जोड़े गए संस्करण')}: {data.processing.ingested_versions}</p>{(['ingestion_jobs','ocr_jobs','index_jobs','ocr_reviews'] as const).map(k=><div key={k}><h3>{name(k)}</h3>{counts(data.processing[k])}</div>)}</article>
      <details><summary>{t('Definitions and retention effects','परिभाषाएँ और रिकॉर्ड अवधि का प्रभाव')}</summary>{Object.entries(data.definitions).map(([k,v])=><p className="mt-2" key={k}>{k}: {v}</p>)}</details><p className="muted">{t('Current votes describe a self-selected sample. Saving or voting does not extend 30-day answer retention; deleted records disappear from these aggregates. No private questions or comments are listed.','वोट स्वयं चुने गए नमूने के हैं। सहेजने या वोट देने से 30 दिन की अवधि नहीं बढ़ती; हटे रिकॉर्ड आँकड़ों से हटते हैं। निजी प्रश्न या टिप्पणियाँ सूचीबद्ध नहीं हैं।')}</p>
    </>}
  </section>
}
