import { useEffect, useRef, useState } from 'react'
import { authorized, type User } from './auth'
import EvidenceQuality, {type Assessment} from './EvidenceQuality'
import Feedback, {type Selection} from './Feedback'
import { translate } from './ui'
type Citation={citation_id:string;marker:number;claim_id:string;start_offset:number;end_offset:number;quote:string|null;claim_text:string|null;metadata:{title:string;issuer:string;version_number:number;pdf_page_number:number|null;source_url:string;publication_date:string|null;effective_date:string|null;version_id:string;extraction_method?:string;ocr_notice?:string;review:{applicability:string}};current_access:{allowed:boolean};provenance:{status:string;reason:string};support:{outcome:string;reason:string;method:string|null}}
export type Answer={id:string;question:string;state:string;status:string|null;error_code:string|null;saved:boolean;can_save:boolean;can_feedback?:boolean;feedback?:Selection|null;source_access_withheld:boolean;current_support_method?:string;result?:{answer:string;claims:{text:string;claim_id?:string}[];limitations:string[]}|null;citations?:Citation[];evidence_quality?:Assessment;claim_checks?:{position:number;retained:boolean;assessment:{outcome:string;reason:string}}[];current_source_warnings?:{warning:string}[];model?:{tag:string;digest:string};timings?:{worker_total_ms:number}}
export default function AnswerDetail({user,run,onUpdate}:{user:User;run:Answer;onUpdate:(v:Answer)=>void}) {
  const t=translate(user),[busy,setBusy]=useState(false),[error,setError]=useState(''),[citation,setCitation]=useState<Citation|null>(null),[text,setText]=useState(''),[stale,setStale]=useState(false)
  const live=useRef(true),inspectionRequest=useRef(0)
  useEffect(()=>{live.current=true;return()=>{live.current=false;inspectionRequest.current++}},[])
  async function reload(){try{const v=await authorized<Answer>(`/ask/history/${run.id}`);if(live.current){onUpdate(v);setStale(false)}}catch{if(live.current)setStale(true)}}
  async function bookmark(){inspectionRequest.current++;setBusy(true);setError('');setCitation(null);setText('')
    try{const v=await authorized<Answer>(`/ask/history/${run.id}/saved`,{method:run.saved?'DELETE':'PUT'});if(live.current)onUpdate(v)}
    catch{setError(t('Bookmark update failed. Retry after refreshing the record.','बुकमार्क नहीं बदल पाया। रिकॉर्ड ताज़ा करके फिर कोशिश करें।'));await reload()}
    finally{setBusy(false)}
  }
  async function inspect(c:Citation){const request=++inspectionRequest.current;setCitation(c);setText('');setError('')
    try{const v=await authorized<{text:string}>(`/ask/history/${run.id}/citations/${c.citation_id}/text`);if(live.current&&request===inspectionRequest.current)setText(v.text)}
    catch{if(!live.current||request!==inspectionRequest.current)return;setCitation(null);setError(t('Source text is unavailable.','स्रोत का पाठ उपलब्ध नहीं है।'));await reload()}
  }
  if(stale)return <div role="alert" className="notice">{t('Record could not be refreshed. Evidence is hidden until access can be checked again.','रिकॉर्ड ताज़ा नहीं हो पाया। अनुमति फिर जाँचे जाने तक साक्ष्य छिपाए गए हैं।')} <button onClick={()=>void reload()}>{t('Retry','फिर कोशिश करें')}</button></div>
  return <div className="space-y-4">
    <p className="notice">{t('Historical sources only: this answer does not establish current entitlement or application advice.','केवल ऐतिहासिक स्रोत: यह उत्तर वर्तमान पात्रता या आवेदन की सलाह साबित नहीं करता।')}</p>
    {(run.saved||run.can_save)&&<button disabled={busy} aria-pressed={run.saved} onClick={()=>void bookmark()}>{busy?t('Updating…','बदल रहा है…'):run.saved?t('Unsave answer','सहेजा उत्तर हटाएँ'):t('Save answer','उत्तर सहेजें')}</button>}
    {run.saved&&<p className="muted">{t('Private bookmark. Expires with the original answer after 30 days; saving does not extend retention.','निजी बुकमार्क। मूल उत्तर के साथ 30 दिन में हटता है; सहेजने से समय नहीं बढ़ता।')}</p>}
    {error&&<p role="alert" className="notice">{error}</p>}
    {run.source_access_withheld?<p className="notice">{t('Source unavailable. Answer text and evidence are withheld under current access rules. The private record is preserved.','स्रोत उपलब्ध नहीं है। मौजूदा अनुमति के अनुसार उत्तर और साक्ष्य नहीं दिखाए जा सकते। निजी रिकॉर्ड सुरक्षित है।')}</p>:run.result&&<><p className="whitespace-pre-wrap">{run.result.answer}</p><ul className="list-disc pl-5">{run.result.limitations.map((v,i)=><li key={i}>{v}</li>)}</ul></>}
    {!run.source_access_withheld&&run.result?.claims.map((c,i)=><article className="border-t pt-3" key={c.claim_id||i}><h3>{t('Claim','दावा')} {i+1}</h3><p>{c.text}</p>{run.citations?.filter(v=>v.claim_id===c.claim_id).map(v=><a className="mr-3" key={v.citation_id} href={`#citation-${v.citation_id}`} onClick={e=>{e.preventDefault();document.getElementById(`citation-${v.citation_id}`)?.focus()}}>{t('Citation','संदर्भ')} [{v.marker}]</a>)}</article>)}
    {!!run.citations?.length&&<section className="space-y-3"><h2>{t('Source evidence','स्रोत के साक्ष्य')}</h2>{run.citations.map(c=><article id={`citation-${c.citation_id}`} tabIndex={-1} className="card space-y-2" key={c.citation_id}><h3>[{c.marker}] {c.metadata.title}</h3><p>{c.metadata.issuer} · {t('Version','संस्करण')} {c.metadata.version_number||t('Recorded','रिकॉर्ड किया गया')} · {t('PDF page','पीडीएफ पृष्ठ')} {c.metadata.pdf_page_number??'TXT'} · {c.metadata.publication_date||t('Date unknown','तिथि अज्ञात')}</p>
      <blockquote>{c.quote||t('Exact excerpt withheld.','सटीक उद्धरण नहीं दिखाया जा सकता।')}</blockquote><a href={c.metadata.source_url} target="_blank" rel="noreferrer">{t('Official source','आधिकारिक स्रोत')}</a>{c.current_access.allowed&&<button className="ml-3" onClick={()=>void inspect(c)}>{t('Inspect cited text','संदर्भ का पाठ देखें')} [{c.marker}]</button>}
      <details><summary>{t('Provenance and support checks','मूल स्रोत और समर्थन की जाँच')}</summary><p>{t('Version ID','संस्करण आईडी')}: {c.metadata.version_id}</p><p>{t('Historical applicability','ऐतिहासिक लागू होने की स्थिति')}: {c.metadata.review.applicability} · {t('Effective date','लागू तिथि')}: {c.metadata.effective_date||t('Unknown','अज्ञात')}</p><p>{t('Extraction','पाठ निष्कर्षण')}: {c.metadata.extraction_method||'digital'} · {c.metadata.ocr_notice}</p><p>{c.provenance.status}: {c.provenance.reason}</p><p>{c.support.outcome}: {c.support.reason} · {c.support.method||t('Not evaluated','जाँच नहीं हुई')}</p><p>{t('Source characters','स्रोत अक्षर')}: [{c.start_offset}, {c.end_offset})</p>{c.support.method&&run.current_support_method&&c.support.method!==run.current_support_method&&<p className="notice">{t('Recorded check uses an earlier method and has not been reassessed.','दर्ज जाँच पुरानी विधि से हुई थी; दोबारा जाँच नहीं हुई।')}</p>}<p>{t('Automated support checks use the same model as generation and do not guarantee truth.','स्वचालित समर्थन जाँच उत्तर वाले मॉडल से ही होती है और सत्य की गारंटी नहीं देती।')}</p></details></article>)}</section>}
    {citation&&<aside className="card" aria-label={t('Source text','स्रोत का पाठ')}><h3>{t('Citation','संदर्भ')} [{citation.marker}]</h3><button onClick={()=>{inspectionRequest.current++;setCitation(null);setText('')}}>{t('Close','बंद करें')}</button>{text?<pre className="whitespace-pre-wrap">{text}</pre>:<p role="status">{t('Loading text…','पाठ खुल रहा है…')}</p>}</aside>}
    {run.claim_checks?.some(c=>!c.retained)&&<details><summary>{t('Omitted candidates','छोड़े गए संभावित दावे')}</summary>{run.claim_checks.filter(c=>!c.retained).map(c=><p key={c.position}>{c.position}: {c.assessment.outcome} · {c.assessment.reason}</p>)}</details>}
    {run.model&&<details><summary>{t('Recorded processing details','प्रसंस्करण का रिकॉर्ड')}</summary><p>{run.model.tag} · {run.model.digest} · {run.timings?.worker_total_ms} ms</p></details>}
    {run.can_feedback&&<Feedback key={run.id} user={user} id={run.id} current={run.feedback||null} onUpdate={v=>onUpdate({...run,feedback:v})} onRefresh={reload}/>}
    {run.evidence_quality&&<EvidenceQuality assessment={run.evidence_quality} language={user.preferred_language==='en'?'en':'hi'}/>}
  </div>
}
