"""durable document ingestion"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0002_documents'
down_revision = '0001_auth'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_scheme_id'), 'documents', ['scheme_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=40), nullable=False),
    sa.Column('original_name', sa.String(length=180), nullable=False),
    sa.Column('format', sa.String(length=3), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sa.String(length=1500), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provenance_status', sa.String(length=12), server_default='unverified', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('extraction_revision', sa.String(length=80), nullable=True),
    sa.Column('chunk_profile', sa.String(length=80), nullable=True),
    sa.CheckConstraint("format IN ('pdf','txt')", name='ck_version_format'),
    sa.CheckConstraint("provenance_status IN ('unverified','verified','rejected')", name='ck_provenance_status'),
    sa.CheckConstraint('version_number > 0 AND size_bytes > 0', name='ck_version_numbers'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum'),
    sa.UniqueConstraint('document_id', 'version_number'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('extracted_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('pdf_page_number', sa.Integer(), nullable=True),
    sa.Column('source_start', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('paragraphs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.CheckConstraint('ordinal > 0 AND (pdf_page_number IS NULL OR pdf_page_number > 0)', name='ck_page_number'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'ordinal')
    )
    op.create_index(op.f('ix_extracted_pages_version_id'), 'extracted_pages', ['version_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('processed_pages', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.Uuid(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('queued','processing','completed','needs_ocr','partial','failed')", name='ck_job_state'),
    sa.CheckConstraint('attempts BETWEEN 0 AND 3 AND progress BETWEEN 0 AND 100', name='ck_job_bounds'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_index(op.f('ix_ingestion_jobs_lease_until'), 'ingestion_jobs', ['lease_until'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_state'), 'ingestion_jobs', ['state'], unique=False)
    op.create_table('version_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_version_id', sa.Uuid(), nullable=False),
    sa.Column('to_version_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('evidence_url', sa.String(length=1500), nullable=False),
    sa.Column('scope_note', sa.Text(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('amends','supersedes')", name='ck_relationship_kind'),
    sa.CheckConstraint('from_version_id <> to_version_id', name='ck_relationship_distinct'),
    sa.ForeignKeyConstraint(['from_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['to_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_version_id', 'to_version_id', 'kind')
    )
    op.create_index(op.f('ix_version_relationships_from_version_id'), 'version_relationships', ['from_version_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section_label', sa.String(length=200), nullable=True),
    sa.Column('continued_clause', sa.Boolean(), nullable=False),
    sa.Column('profile', sa.String(length=80), nullable=False),
    sa.CheckConstraint('start_offset >= 0 AND end_offset > start_offset', name='ck_chunk_offsets'),
    sa.ForeignKeyConstraint(['page_id'], ['extracted_pages.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'ordinal')
    )
    op.create_index(op.f('ix_chunks_page_id'), 'chunks', ['page_id'], unique=False)
    op.create_index(op.f('ix_chunks_version_id'), 'chunks', ['version_id'], unique=False)
    # Original bytes and source metadata are immutable; verification/derived revisions may change.
    op.execute("""CREATE FUNCTION protect_document_version() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF ROW(NEW.document_id, NEW.version_number, NEW.checksum, NEW.storage_key, NEW.original_name,
             NEW.format, NEW.size_bytes, NEW.metadata_snapshot, NEW.source_url, NEW.language,
             NEW.publication_date, NEW.effective_date, NEW.uploaded_by, NEW.ingested_at)
         IS DISTINCT FROM
         ROW(OLD.document_id, OLD.version_number, OLD.checksum, OLD.storage_key, OLD.original_name,
             OLD.format, OLD.size_bytes, OLD.metadata_snapshot, OLD.source_url, OLD.language,
             OLD.publication_date, OLD.effective_date, OLD.uploaded_by, OLD.ingested_at) THEN
        RAISE EXCEPTION 'Original version metadata is immutable';
      END IF;
      RETURN NEW;
    END $$""")
    op.execute("CREATE TRIGGER immutable_document_version BEFORE UPDATE ON document_versions FOR EACH ROW EXECUTE FUNCTION protect_document_version()")

def downgrade():
    op.execute("DROP TRIGGER immutable_document_version ON document_versions")
    op.execute("DROP FUNCTION protect_document_version()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_version_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_page_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_version_relationships_from_version_id'), table_name='version_relationships')
    op.drop_table('version_relationships')
    op.drop_index(op.f('ix_ingestion_jobs_state'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_lease_until'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_extracted_pages_version_id'), table_name='extracted_pages')
    op.drop_table('extracted_pages')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_scheme_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('schemes')
    # ### end Alembic commands ###
