"""audited eligibility and durable vector generations"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0003_retrieval'
down_revision = '0002_documents'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_generations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.Uuid(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('queued','processing','ready','failed') AND attempts BETWEEN 0 AND 3 AND processed >= 0 AND total >= 0", name='ck_index_job'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_generations_state'), 'index_generations', ['state'], unique=False)
    op.create_table('index_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_single_index'),
    sa.ForeignKeyConstraint(['active_id'], ['index_generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligibility_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reuse_status', sa.String(length=30), nullable=False),
    sa.Column('applicability', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=1500), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('verified','rejected') AND reuse_status IN ('permission_recorded','local_reference_only','not_assessed') AND applicability IN ('historical','unknown','current_verified')", name='ck_review_choices'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_reviews_version_id'), 'eligibility_reviews', ['version_id'], unique=False)
    op.create_table('index_passages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section_label', sa.String(length=200), nullable=True),
    sa.Column('continued_clause', sa.Boolean(), nullable=False),
    sa.Column('profile', sa.String(length=80), nullable=False),
    sa.CheckConstraint('start_offset >= 0 AND end_offset > start_offset', name='ck_index_span'),
    sa.ForeignKeyConstraint(['generation_id'], ['index_generations.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['extracted_pages.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_passages_generation_id'), 'index_passages', ['generation_id'], unique=False)
    op.create_index(op.f('ix_index_passages_page_id'), 'index_passages', ['page_id'], unique=False)
    op.create_index(op.f('ix_index_passages_version_id'), 'index_passages', ['version_id'], unique=False)
    op.execute("""CREATE FUNCTION protect_eligibility_review() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'eligibility review is append-only'; END; $$""")
    op.execute("CREATE TRIGGER eligibility_review_immutable BEFORE UPDATE OR DELETE ON eligibility_reviews FOR EACH ROW EXECUTE FUNCTION protect_eligibility_review()")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_index_passages_version_id'), table_name='index_passages')
    op.drop_index(op.f('ix_index_passages_page_id'), table_name='index_passages')
    op.drop_index(op.f('ix_index_passages_generation_id'), table_name='index_passages')
    op.drop_table('index_passages')
    op.drop_index(op.f('ix_eligibility_reviews_version_id'), table_name='eligibility_reviews')
    op.drop_table('eligibility_reviews')
    op.drop_table('index_state')
    op.drop_index(op.f('ix_index_generations_state'), table_name='index_generations')
    op.drop_table('index_generations')
    op.execute('DROP FUNCTION protect_eligibility_review()')
    # ### end Alembic commands ###
